
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gruhayn
 */
public class MainMenu extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private static boolean blocked=true;
    private static String[] yariyillar;
    
    public void setBlocked(boolean blocked)
    {
        this.blocked = blocked;
    }
    
    /**
     * Creates new form Ogrenci
     */
    @SuppressWarnings("unchecked")
    public MainMenu() {
        initComponents(); 
       
    }
    private void setJLabelMevcutYariyil()
    {
        String currentYear = (new Functions()).getCurrentYear();
        System.out.println(currentYear);
        if(currentYear==null || currentYear.equals(""))
        {
            this.jLabelMevcutYariyil.setText("Şu anda hiçbir yarıyılda kayıtlı değilsiniz.Yeni yarıyıl ekleyiniz ve ya yarıyıla geçiş yapınız.");
            blocked=true;
        }
        else{
            System.out.println("qosuldu");
            this.jLabelMevcutYariyil.setText(currentYear);
            this.setBlocked(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonYeniKayitEkle = new javax.swing.JButton();
        jButtonOgrenciArama = new javax.swing.JButton();
        jButtonOgrenciBilgiler = new javax.swing.JButton();
        jButtonOgrenciSil = new javax.swing.JButton();
        jButtonOgrenciBilgisiDuzenle = new javax.swing.JButton();
        jButtonSinavEkle = new javax.swing.JButton();
        jButtonSinavIsle = new javax.swing.JButton();
        jButtonDevamsizlikIsle = new javax.swing.JButton();
        jButtonDevamsizlikIsle1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonPersonelKaydi = new javax.swing.JButton();
        jButtonPersonelArama = new javax.swing.JButton();
        jButtonPersonelBilgisiDuzenle = new javax.swing.JButton();
        jButtonMaasOdeme = new javax.swing.JButton();
        jButtonPersonelBilgileri = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonTumTaksitler = new javax.swing.JButton();
        jButtonGelirlerGiderler = new javax.swing.JButton();
        jButtonGiderEkle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonOgrenciListesi = new javax.swing.JButton();
        jButtonSinifListesi = new javax.swing.JButton();
        jButtonTelefonListesi = new javax.swing.JButton();
        jButtonAdresListesi = new javax.swing.JButton();
        jButtonDevamsizlikListesi = new javax.swing.JButton();
        jButtonSinavSonuclariListesi = new javax.swing.JButton();
        jButtonGrupListesi = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonTaksitliSatis = new javax.swing.JButton();
        jButtonTaksitliSatis1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonGrupIslemleri = new javax.swing.JButton();
        jButtonSinifIslemleri = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonOgrenciOzelRaporlama = new javax.swing.JButton();
        jButtonMuhasebeRaporlari = new javax.swing.JButton();
        jButtonMuhasebeRaporlari1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonOgrenciOzelRaporlama1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldYariyilIsmi = new javax.swing.JTextField();
        jButtonOgrenciOzelRaporlama2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMevcutYariyil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));

        jButtonYeniKayitEkle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonYeniKayitEkle.setText("Yeni Kayıt Ekle");
        jButtonYeniKayitEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYeniKayitEkleActionPerformed(evt);
            }
        });

        jButtonOgrenciArama.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciArama.setText("Öğrenci Arama");
        jButtonOgrenciArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciAramaActionPerformed(evt);
            }
        });

        jButtonOgrenciBilgiler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciBilgiler.setText("Öğrenci Bilgileri");
        jButtonOgrenciBilgiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciBilgilerActionPerformed(evt);
            }
        });

        jButtonOgrenciSil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciSil.setText("Öğrenci Sil");
        jButtonOgrenciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciSilActionPerformed(evt);
            }
        });

        jButtonOgrenciBilgisiDuzenle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciBilgisiDuzenle.setText("Öğrenci Bilgisi Düzenle");
        jButtonOgrenciBilgisiDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciBilgisiDuzenleActionPerformed(evt);
            }
        });

        jButtonSinavEkle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSinavEkle.setText("Sınav Ekle/Sil");
        jButtonSinavEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinavEkleActionPerformed(evt);
            }
        });

        jButtonSinavIsle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSinavIsle.setText("Sınav İşle");
        jButtonSinavIsle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinavIsleActionPerformed(evt);
            }
        });

        jButtonDevamsizlikIsle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonDevamsizlikIsle.setText("Devamsızlık İşle");
        jButtonDevamsizlikIsle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevamsizlikIsleActionPerformed(evt);
            }
        });

        jButtonDevamsizlikIsle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonDevamsizlikIsle1.setText("Sınıfa Öğrenci Ekle/Sınıftan Öğrenci Çıkar");
        jButtonDevamsizlikIsle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevamsizlikIsle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonYeniKayitEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOgrenciBilgiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOgrenciArama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOgrenciSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOgrenciBilgisiDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSinavEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSinavIsle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevamsizlikIsle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevamsizlikIsle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonYeniKayitEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOgrenciBilgiler, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOgrenciArama, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOgrenciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOgrenciBilgisiDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSinavEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSinavIsle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDevamsizlikIsle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDevamsizlikIsle1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Öğrenci", jPanel2);

        jButtonPersonelKaydi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonPersonelKaydi.setText("Personel Kaydı");
        jButtonPersonelKaydi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonelKaydiActionPerformed(evt);
            }
        });

        jButtonPersonelArama.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonPersonelArama.setText("Personel Arama");
        jButtonPersonelArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonelAramaActionPerformed(evt);
            }
        });

        jButtonPersonelBilgisiDuzenle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonPersonelBilgisiDuzenle.setText("Personel Bilgisi Düzenle");
        jButtonPersonelBilgisiDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonelBilgisiDuzenleActionPerformed(evt);
            }
        });

        jButtonMaasOdeme.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonMaasOdeme.setText("Maaş Ödeme");
        jButtonMaasOdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaasOdemeActionPerformed(evt);
            }
        });

        jButtonPersonelBilgileri.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonPersonelBilgileri.setText("Personel Bilgileri");
        jButtonPersonelBilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonelBilgileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonPersonelBilgisiDuzenle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jButtonPersonelArama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPersonelBilgileri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPersonelKaydi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMaasOdeme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1270, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPersonelKaydi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPersonelBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButtonPersonelArama, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPersonelBilgisiDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMaasOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Personel", jPanel3);

        jButtonTumTaksitler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonTumTaksitler.setText("Tüm Taksitler");
        jButtonTumTaksitler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTumTaksitlerActionPerformed(evt);
            }
        });

        jButtonGelirlerGiderler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonGelirlerGiderler.setText("Gelirler/Giderler");
        jButtonGelirlerGiderler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGelirlerGiderlerActionPerformed(evt);
            }
        });

        jButtonGiderEkle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonGiderEkle.setText("Gider Ekle");
        jButtonGiderEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiderEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTumTaksitler, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGelirlerGiderler, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGiderEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1324, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTumTaksitler, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGelirlerGiderler, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGiderEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Muhasebe", jPanel4);

        jButtonOgrenciListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciListesi.setText("Öğrenci Listesi");
        jButtonOgrenciListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciListesiActionPerformed(evt);
            }
        });

        jButtonSinifListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSinifListesi.setText("Sınıf Listesi");
        jButtonSinifListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinifListesiActionPerformed(evt);
            }
        });

        jButtonTelefonListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonTelefonListesi.setText("Telefon Listesi");
        jButtonTelefonListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelefonListesiActionPerformed(evt);
            }
        });

        jButtonAdresListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonAdresListesi.setText("Adres Listesi");
        jButtonAdresListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdresListesiActionPerformed(evt);
            }
        });

        jButtonDevamsizlikListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonDevamsizlikListesi.setText("Devamsızlık Listesi");
        jButtonDevamsizlikListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevamsizlikListesiActionPerformed(evt);
            }
        });

        jButtonSinavSonuclariListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSinavSonuclariListesi.setText("Sınav Sonuçları Listesi");
        jButtonSinavSonuclariListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinavSonuclariListesiActionPerformed(evt);
            }
        });

        jButtonGrupListesi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonGrupListesi.setText("Grup Listesi");
        jButtonGrupListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrupListesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOgrenciListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSinifListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTelefonListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdresListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevamsizlikListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSinavSonuclariListesi, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jButtonGrupListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1283, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOgrenciListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSinifListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTelefonListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdresListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDevamsizlikListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSinavSonuclariListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGrupListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Listeler", jPanel5);

        jButtonTaksitliSatis.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonTaksitliSatis.setText("Taksitli Satış");
        jButtonTaksitliSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaksitliSatisActionPerformed(evt);
            }
        });

        jButtonTaksitliSatis1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonTaksitliSatis1.setText("Direkt Satış");
        jButtonTaksitliSatis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaksitliSatis1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTaksitliSatis, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jButtonTaksitliSatis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1222, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTaksitliSatis, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTaksitliSatis1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Satış", jPanel6);

        jButtonGrupIslemleri.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonGrupIslemleri.setText("Grup İşlemleri");
        jButtonGrupIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrupIslemleriActionPerformed(evt);
            }
        });

        jButtonSinifIslemleri.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSinifIslemleri.setText("Sınıf İşlemleri");
        jButtonSinifIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinifIslemleriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGrupIslemleri, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jButtonSinifIslemleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1293, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGrupIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSinifIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Grup/Sınıf", jPanel7);

        jButtonOgrenciOzelRaporlama.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciOzelRaporlama.setText("Öğrenci Özel Raporlama");
        jButtonOgrenciOzelRaporlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciOzelRaporlamaActionPerformed(evt);
            }
        });

        jButtonMuhasebeRaporlari.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonMuhasebeRaporlari.setText("Muhasebe Raporları");
        jButtonMuhasebeRaporlari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuhasebeRaporlariActionPerformed(evt);
            }
        });

        jButtonMuhasebeRaporlari1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonMuhasebeRaporlari1.setText("Sınav sonuçları yazdır");
        jButtonMuhasebeRaporlari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuhasebeRaporlari1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOgrenciOzelRaporlama, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMuhasebeRaporlari, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMuhasebeRaporlari1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1208, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOgrenciOzelRaporlama, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMuhasebeRaporlari, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMuhasebeRaporlari1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Raporlar", jPanel8);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jButtonOgrenciOzelRaporlama1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciOzelRaporlama1.setText("Geçiş Yap");
        jButtonOgrenciOzelRaporlama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciOzelRaporlama1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Geçiş Yapmak İstediğiniz Yarıyılı Seçiniz ve Geçiş Yap Butonuna Tıklayınız.");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Yeni Yarıyıl Eklemek İçin Eklemek İstediğiniz Yarıyılın İsmini Giriniz ve Ekle Butonuna Basınız.");

        jButtonOgrenciOzelRaporlama2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOgrenciOzelRaporlama2.setText("Ekle");
        jButtonOgrenciOzelRaporlama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciOzelRaporlama2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 403, Short.MAX_VALUE)
                    .addComponent(jTextFieldYariyilIsmi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOgrenciOzelRaporlama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOgrenciOzelRaporlama2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOgrenciOzelRaporlama1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldYariyilIsmi, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButtonOgrenciOzelRaporlama2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
        );

        jTabbedPane.addTab("Yarıyıl İşlemleri", jPanel1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Mevcut Yarıyıl:");

        jLabelMevcutYariyil.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelMevcutYariyil.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMevcutYariyil, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabelMevcutYariyil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonYeniKayitEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYeniKayitEkleActionPerformed
        if(!blocked)
        {
            YeniKayitEkle yke=new YeniKayitEkle();
            yke.setVisible(true);
            this.setVisible(true);
            yke.setAlwaysOnTop(true);
            yke.setComboBoxs();
            yke.setOgrNo();
        }
    }//GEN-LAST:event_jButtonYeniKayitEkleActionPerformed

    private void jButtonOgrenciBilgilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciBilgilerActionPerformed
        if(!blocked)
        {
            OgrenciBilgileri yke=new OgrenciBilgileri();
            yke.setVisible(true);
            yke.setTable();
            yke.setComboBoxs();
            this.setVisible(true);
            yke.setAlwaysOnTop(true);
            
        }
    }//GEN-LAST:event_jButtonOgrenciBilgilerActionPerformed

    private void jButtonOgrenciAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciAramaActionPerformed
        this.jButtonOgrenciBilgilerActionPerformed(evt);
    }//GEN-LAST:event_jButtonOgrenciAramaActionPerformed

    private void jButtonOgrenciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciSilActionPerformed
        this.jButtonOgrenciBilgilerActionPerformed(evt);        
    }//GEN-LAST:event_jButtonOgrenciSilActionPerformed

    private void jButtonOgrenciBilgisiDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciBilgisiDuzenleActionPerformed
        this.jButtonOgrenciBilgilerActionPerformed(evt);        
    }//GEN-LAST:event_jButtonOgrenciBilgisiDuzenleActionPerformed

    private void jButtonSinavEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinavEkleActionPerformed
        if(!blocked)
        {
            SinavEkle yke=new SinavEkle();
            yke.setVisible(true);
            this.setVisible(true);
            yke.setAlwaysOnTop(true);
            yke.setTable();
            yke.setComboBoxs();
        }
    }//GEN-LAST:event_jButtonSinavEkleActionPerformed

    private void jButtonSinavIsleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinavIsleActionPerformed
        if(!blocked)
        {
        SinavIsle yke=new SinavIsle();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        yke.setComboBoxs();
        yke.setTable1();
        }
    }//GEN-LAST:event_jButtonSinavIsleActionPerformed

    private void jButtonDevamsizlikIsleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevamsizlikIsleActionPerformed
        if(!blocked)
        {
        DevamsizlikIsle yke=new DevamsizlikIsle();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        yke.setTable();
        yke.setComboBoxs();
        }
    }//GEN-LAST:event_jButtonDevamsizlikIsleActionPerformed

    private void jButtonPersonelKaydiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonelKaydiActionPerformed
        if(!blocked)
        {
        PersonelKaydi yke=new PersonelKaydi();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setPerNo();
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonPersonelKaydiActionPerformed

    private void jButtonPersonelAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonelAramaActionPerformed
        if(!blocked)
        {
        PersonelBilgisi yke=new PersonelBilgisi();
        yke.setVisible(true);
        yke.setTable();
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonPersonelAramaActionPerformed

    private void jButtonPersonelBilgisiDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonelBilgisiDuzenleActionPerformed
        this.jButtonPersonelAramaActionPerformed(evt);
    }//GEN-LAST:event_jButtonPersonelBilgisiDuzenleActionPerformed

    private void jButtonMaasOdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaasOdemeActionPerformed
        this.jButtonPersonelAramaActionPerformed(evt);
    }//GEN-LAST:event_jButtonMaasOdemeActionPerformed

    private void jButtonTumTaksitlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTumTaksitlerActionPerformed
        if(!blocked)
        {
        TumTaksitler yke=new TumTaksitler();
        yke.setComboBoxs();
        yke.setTableOdenmemisTakstiler();
        yke.setTableOdenmisTaksitler();
        yke.setTableTumTaksitler();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonTumTaksitlerActionPerformed

    private void jButtonGelirlerGiderlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGelirlerGiderlerActionPerformed
        if(!blocked)
        {
        Gelirler_Giderler yke=new Gelirler_Giderler();
        yke.setTable();
        yke.setTable2();
        yke.setTableGelir();
        yke.setTableGider();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonGelirlerGiderlerActionPerformed

    private void jButtonGiderEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiderEkleActionPerformed
        if(!blocked)
        {
        GiderEkle yke=new GiderEkle();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonGiderEkleActionPerformed

    private void jButtonOgrenciListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciListesiActionPerformed
        if(!blocked)
        {
            OgrenciBilgileri yke=new OgrenciBilgileri();
            yke.setVisible(true);
            this.setVisible(true);
            yke.setAlwaysOnTop(true);
            yke.setTable();
            yke.setComboBoxs();
        }
    }//GEN-LAST:event_jButtonOgrenciListesiActionPerformed

    private void jButtonSinifListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinifListesiActionPerformed
        if(!blocked)
        {
        SinifListesi yke=new SinifListesi();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        yke.setComboBoxs();
        yke.setTable();
        }
    }//GEN-LAST:event_jButtonSinifListesiActionPerformed

    private void jButtonTelefonListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelefonListesiActionPerformed
        if(!blocked)
        {
        TelefonListesi yke=new TelefonListesi();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        yke.setTable();
        yke.setComboBoxs();
        }
    }//GEN-LAST:event_jButtonTelefonListesiActionPerformed

    private void jButtonAdresListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdresListesiActionPerformed
        if(!blocked)
        {
        AdresListesi yke=new AdresListesi();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        yke.setTable();
        yke.setComboBoxs();
        }
    }//GEN-LAST:event_jButtonAdresListesiActionPerformed

    private void jButtonDevamsizlikListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevamsizlikListesiActionPerformed
        if(!blocked)
        {
        DevamsizlikListesi yke=new DevamsizlikListesi();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        yke.setTable();
        yke.setComboBoxs();
        }
    }//GEN-LAST:event_jButtonDevamsizlikListesiActionPerformed

    private void jButtonSinavSonuclariListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinavSonuclariListesiActionPerformed
        if(!blocked)
        {
        SinavSonuclariListesi yke=new SinavSonuclariListesi();
        yke.setTable();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonSinavSonuclariListesiActionPerformed

    private void jButtonGrupListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrupListesiActionPerformed
        this.jButtonGrupIslemleriActionPerformed(evt);
    }//GEN-LAST:event_jButtonGrupListesiActionPerformed

    private void jButtonTaksitliSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaksitliSatisActionPerformed
        if(!blocked)
        {
        TaksitliSatis yke=new TaksitliSatis();
        yke.setTable();
        yke.setTable2();
        yke.setComboBoxs();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonTaksitliSatisActionPerformed

    private void jButtonTaksitliSatis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaksitliSatis1ActionPerformed
        this.jButtonTaksitliSatisActionPerformed(evt);
    }//GEN-LAST:event_jButtonTaksitliSatis1ActionPerformed

    private void jButtonGrupIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrupIslemleriActionPerformed
        if(!blocked)
        {
        GrupListesi yke=new GrupListesi();
        yke.setTable();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonGrupIslemleriActionPerformed

    private void jButtonSinifIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinifIslemleriActionPerformed
        this.jButtonSinifListesiActionPerformed(evt);
    }//GEN-LAST:event_jButtonSinifIslemleriActionPerformed

    private void jButtonOgrenciOzelRaporlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciOzelRaporlamaActionPerformed
        if(!blocked)
        {
            OgrenciOzelRaporlama yke=new OgrenciOzelRaporlama();
            yke.setVisible(true);
            this.setVisible(true);
            yke.setAlwaysOnTop(true);
            yke.setComboBoxs();
            yke.setTable();
        }
    }//GEN-LAST:event_jButtonOgrenciOzelRaporlamaActionPerformed

    private void jButtonMuhasebeRaporlariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuhasebeRaporlariActionPerformed
        if(!blocked)
        {
        MuhasebeRaporlari yke=new MuhasebeRaporlari();
        yke.setVisible(true);
        this.setVisible(true);
        yke.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_jButtonMuhasebeRaporlariActionPerformed

    private void jButtonOgrenciOzelRaporlama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciOzelRaporlama2ActionPerformed
        this.setAlwaysOnTop(false);
        if(!jTextFieldYariyilIsmi.getText().equals(""))
        {
            Object[] options = {"Evet",
                    "Hayır"};
            int n = JOptionPane.showOptionDialog(this,
            "Yarıyıl eklemek istediğinizden eminmisiniz?",
            "",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[1]);
            if(n==0)
            {   
                boolean var=true;
                for(String i : yariyillar){
                    if(i.equals(jTextFieldYariyilIsmi.getText()))
                    {
                        var=false;
                    }
                }
                if(var)
                {
                    try {
                        (new Functions()).yeniYariyilEkle(this.jTextFieldYariyilIsmi.getText());
                        this.jComboBox1.removeAllItems();
                        yariyillar=(new Functions()).getYariyillar();
                        for(String s:yariyillar){
                            this.jComboBox1.addItem(s);
                        }
                        this.jTextFieldYariyilIsmi.setText("");
                        JOptionPane.showMessageDialog(null, "Yarıyıl eklendi.", null , JOptionPane.DEFAULT_OPTION);                                       
                    
                    } catch (IOException ex) {
                        Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Bu isimde yarıyıl mevcuttur.", null , JOptionPane.DEFAULT_OPTION);                                       
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Yarıyıl ismi boş bırakılamaz.", null , JOptionPane.DEFAULT_OPTION);                       
        }
    }//GEN-LAST:event_jButtonOgrenciOzelRaporlama2ActionPerformed

    private void jButtonOgrenciOzelRaporlama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciOzelRaporlama1ActionPerformed
        (new Functions()).setActiveYariyil(String.valueOf(this.jComboBox1.getSelectedItem().toString()));
        this.setJLabelMevcutYariyil();
    }//GEN-LAST:event_jButtonOgrenciOzelRaporlama1ActionPerformed

    private void jButtonPersonelBilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonelBilgileriActionPerformed
        this.jButtonPersonelAramaActionPerformed(evt);
    }//GEN-LAST:event_jButtonPersonelBilgileriActionPerformed

    private void jButtonDevamsizlikIsle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevamsizlikIsle1ActionPerformed
        this.jButtonSinifListesiActionPerformed(evt);
    }//GEN-LAST:event_jButtonDevamsizlikIsle1ActionPerformed

    private void jButtonMuhasebeRaporlari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuhasebeRaporlari1ActionPerformed
        this.jButtonSinavSonuclariListesiActionPerformed(evt);
    }//GEN-LAST:event_jButtonMuhasebeRaporlari1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private Object ex;
            @SuppressWarnings("unchecked")
            public void run() {
                try { 
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    MainMenu mm = new MainMenu();
                    mm.setVisible(true);
                                
                    mm.setJLabelMevcutYariyil();
                    mm.jComboBox1.removeAllItems();
                    yariyillar=(new Functions()).getYariyillar();
                    for(String s:yariyillar){
                        mm.jComboBox1.addItem(s);
                    }
                    
                    
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);    
                } catch(IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ignored){} catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdresListesi;
    private javax.swing.JButton jButtonDevamsizlikIsle;
    private javax.swing.JButton jButtonDevamsizlikIsle1;
    private javax.swing.JButton jButtonDevamsizlikListesi;
    private javax.swing.JButton jButtonGelirlerGiderler;
    private javax.swing.JButton jButtonGiderEkle;
    private javax.swing.JButton jButtonGrupIslemleri;
    private javax.swing.JButton jButtonGrupListesi;
    private javax.swing.JButton jButtonMaasOdeme;
    private javax.swing.JButton jButtonMuhasebeRaporlari;
    private javax.swing.JButton jButtonMuhasebeRaporlari1;
    private javax.swing.JButton jButtonOgrenciArama;
    private javax.swing.JButton jButtonOgrenciBilgiler;
    private javax.swing.JButton jButtonOgrenciBilgisiDuzenle;
    private javax.swing.JButton jButtonOgrenciListesi;
    private javax.swing.JButton jButtonOgrenciOzelRaporlama;
    private javax.swing.JButton jButtonOgrenciOzelRaporlama1;
    private javax.swing.JButton jButtonOgrenciOzelRaporlama2;
    private javax.swing.JButton jButtonOgrenciSil;
    private javax.swing.JButton jButtonPersonelArama;
    private javax.swing.JButton jButtonPersonelBilgileri;
    private javax.swing.JButton jButtonPersonelBilgisiDuzenle;
    private javax.swing.JButton jButtonPersonelKaydi;
    private javax.swing.JButton jButtonSinavEkle;
    private javax.swing.JButton jButtonSinavIsle;
    private javax.swing.JButton jButtonSinavSonuclariListesi;
    private javax.swing.JButton jButtonSinifIslemleri;
    private javax.swing.JButton jButtonSinifListesi;
    private javax.swing.JButton jButtonTaksitliSatis;
    private javax.swing.JButton jButtonTaksitliSatis1;
    private javax.swing.JButton jButtonTelefonListesi;
    private javax.swing.JButton jButtonTumTaksitler;
    private javax.swing.JButton jButtonYeniKayitEkle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMevcutYariyil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldYariyilIsmi;
    // End of variables declaration//GEN-END:variables

}
