
import datechooser.beans.DateChooserCombo;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gruhayn
 */
public class PersonelKaydi extends javax.swing.JFrame {

    private boolean duzenle=false;

    /**
     * Creates new form PersonelKaydi
     */
    public PersonelKaydi() {
        initComponents();
    }

    public void setjCheckBoxOgretmenmi(JCheckBox jCheckBoxOgretmenmi) {
        this.jCheckBoxOgretmenmi = jCheckBoxOgretmenmi;
    }

    public void setjLabelPersonelNo(JLabel jLabelPersonelNo) {
        this.jLabelPersonelNo = jLabelPersonelNo;
    }

    public void setjTextFieldBitirdigiOkul(JTextField jTextFieldBitirdigiOkul) {
        this.jTextFieldBitirdigiOkul = jTextFieldBitirdigiOkul;
    }

    public void setjTextFieldBrans(JTextField jTextFieldBrans) {
        this.jTextFieldBrans = jTextFieldBrans;
    }

    public void setjTextFieldMaas(JTextField jTextFieldMaas) {
        this.jTextFieldMaas = jTextFieldMaas;
    }

    public void setjTextFieldOgrenciAd(JTextField jTextFieldOgrenciAd) {
        this.jTextFieldOgrenciAd = jTextFieldOgrenciAd;
    }

    public void setjTextFieldOgrenciAdres(JTextField jTextFieldOgrenciAdres) {
        this.jTextFieldOgrenciAdres = jTextFieldOgrenciAdres;
    }

    public void setjTextFieldOgrenciSoyad(JTextField jTextFieldOgrenciSoyad) {
        this.jTextFieldOgrenciSoyad = jTextFieldOgrenciSoyad;
    }

    public void setjTextFieldOgrenciTel1(JTextField jTextFieldOgrenciTel1) {
        this.jTextFieldOgrenciTel1 = jTextFieldOgrenciTel1;
    }

    public void setjTextFieldOgrenciTel2(JTextField jTextFieldOgrenciTel2) {
        this.jTextFieldOgrenciTel2 = jTextFieldOgrenciTel2;
    }

    public void setjTextFieldOgrenciTelNumarasi(JTextField jTextFieldOgrenciTelNumarasi) {
        this.jTextFieldOgrenciTelNumarasi = jTextFieldOgrenciTelNumarasi;
    }
    
    

    public JLabel getjLabelPersonelNo() {
        return jLabelPersonelNo;
    }
    
    public DateChooserCombo getDateChooserComboDogumTarihi() {
        return dateChooserComboDogumTarihi;
    }

    public DateChooserCombo getDateChooserComboIseBasladigiTarih() {
        return dateChooserComboIseBasladigiTarih;
    }

    public JCheckBox getjCheckBoxOgretmenmi() {
        return jCheckBoxOgretmenmi;
    }

    public JTextField getjTextFieldBitirdigiOkul() {
        return jTextFieldBitirdigiOkul;
    }

    public JTextField getjTextFieldBrans() {
        return jTextFieldBrans;
    }

    public JTextField getjTextFieldMaas() {
        return jTextFieldMaas;
    }

    public JTextField getjTextFieldOgrenciAd() {
        return jTextFieldOgrenciAd;
    }

    public JTextField getjTextFieldOgrenciAdres() {
        return jTextFieldOgrenciAdres;
    }

    public JTextField getjTextFieldOgrenciSoyad() {
        return jTextFieldOgrenciSoyad;
    }

    public JTextField getjTextFieldOgrenciTel1() {
        return jTextFieldOgrenciTel1;
    }

    public JTextField getjTextFieldOgrenciTel2() {
        return jTextFieldOgrenciTel2;
    }

    public JTextField getjTextFieldOgrenciTelNumarasi() {
        return jTextFieldOgrenciTelNumarasi;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBasliq = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldOgrenciAd = new javax.swing.JTextField();
        jTextFieldOgrenciSoyad = new javax.swing.JTextField();
        jTextFieldOgrenciTelNumarasi = new javax.swing.JTextField();
        jTextFieldOgrenciTel1 = new javax.swing.JTextField();
        jTextFieldOgrenciTel2 = new javax.swing.JTextField();
        jLabeldogum = new javax.swing.JLabel();
        dateChooserComboIseBasladigiTarih = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBitirdigiOkul = new javax.swing.JTextField();
        jLabeltarih = new javax.swing.JLabel();
        dateChooserComboDogumTarihi = new datechooser.beans.DateChooserCombo();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldOgrenciAdres = new javax.swing.JTextField();
        jTextFieldBrans = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBoxOgretmenmi = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldMaas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabelPersonelNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelBasliq.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelBasliq.setText("Yeni Kayıt Ekle");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Personel Bilgileri");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("*Ad:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("*Soyad:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("*Tel Numarası:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Tel 1:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Tel 2:");

        jTextFieldOgrenciAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOgrenciAdActionPerformed(evt);
            }
        });

        jLabeldogum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabeldogum.setText("Doğum Tarihi:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Bitirdiği Okul:");

        jTextFieldBitirdigiOkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBitirdigiOkulActionPerformed(evt);
            }
        });

        jLabeltarih.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabeltarih.setText("İşe Başladığı Tarih:");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Adres:");

        jTextFieldOgrenciAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOgrenciAdresActionPerformed(evt);
            }
        });

        jTextFieldBrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBransActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxOgretmenmi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBoxOgretmenmi.setText("Öğretmen");
        jCheckBoxOgretmenmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOgretmenmiActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setText("*Maaş:");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setText("Branş:");

        jTextFieldMaas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Personel Numarası:");

        jLabelPersonelNo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldOgrenciTel2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldOgrenciTel1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldOgrenciTelNumarasi))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldOgrenciSoyad))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldOgrenciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldOgrenciAdres)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelPersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxOgretmenmi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabeltarih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabeldogum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBitirdigiOkul, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateChooserComboDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateChooserComboIseBasladigiTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBrans, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBasliq, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelBasliq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeldogum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(dateChooserComboDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltarih, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserComboIseBasladigiTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBitirdigiOkul, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBrans, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jCheckBoxOgretmenmi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOgrenciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOgrenciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOgrenciTelNumarasi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOgrenciTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOgrenciTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOgrenciAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOgrenciAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOgrenciAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOgrenciAdActionPerformed

    private void jTextFieldBitirdigiOkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBitirdigiOkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBitirdigiOkulActionPerformed

    private void jTextFieldBransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBransActionPerformed

    private void jCheckBoxOgretmenmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOgretmenmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOgretmenmiActionPerformed

    private void jTextFieldMaasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaasActionPerformed

    private void jTextFieldOgrenciAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOgrenciAdresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOgrenciAdresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setAlwaysOnTop(false);
        if(this.jTextFieldOgrenciAd.getText().equals("") || this.jTextFieldOgrenciSoyad.getText().equals("") || this.jTextFieldOgrenciTelNumarasi.getText().equals("") || this.jTextFieldMaas.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Önünde yıldız işareti olanları doldurmanız gerekmektedir.", null , JOptionPane.INFORMATION_MESSAGE);            
        }
        else
        {
            try{ 
                if(!(this.jTextFieldOgrenciTel1.getText().equals(""))) {
                    Integer.parseInt(this.jTextFieldOgrenciTel1.getText());
                }
                if(!(this.jTextFieldOgrenciTel2.getText().equals(""))) {
                    Integer.parseInt(this.jTextFieldOgrenciTel2.getText());
                }
                if(!(this.jTextFieldOgrenciTelNumarasi.getText().equals(""))) {
                    Integer.parseInt(this.jTextFieldOgrenciTelNumarasi.getText());
                }
                if(!(this.jTextFieldMaas.getText().equals("")))
                {
                    Integer.parseInt(this.jTextFieldMaas.getText());
                }
                (new Functions()).personelEkle(this,duzenle);
                if(!duzenle) {
                    (new Functions()).artirPersonelNumarasi(this.jLabelPersonelNo.getText());
                    JOptionPane.showMessageDialog(null, "Personel kaydedildi.Yeni personel kaydedebilirsiniz.", null , JOptionPane.DEFAULT_OPTION);
                    PersonelKaydi yke=new PersonelKaydi();
                    yke.setVisible(true);
                    this.setVisible(false);
                    yke.setPerNo();
                    yke.setAlwaysOnTop(true);
                }   
                else{
                    JOptionPane.showMessageDialog(null, "Personel bilgisi düzenlendi.", null , JOptionPane.DEFAULT_OPTION);     
                    this.setVisible(false);
                    PersonelBilgisi yke=new PersonelBilgisi();
                    yke.setVisible(true);
                    yke.setTable();
                    this.setVisible(false);
                    yke.setAlwaysOnTop(true);
                }
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Telefon numaraları ve maaş sadece rakamlardan oluşmalıdır.+(artı),-(eksi), (boşluk karakteri) kullanmayınız.", null , JOptionPane.INFORMATION_MESSAGE);                            
            }
            
        }
        this.setAlwaysOnTop(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try { 
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch(Exception ignored){}
                new PersonelKaydi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public datechooser.beans.DateChooserCombo dateChooserComboDogumTarihi;
    public datechooser.beans.DateChooserCombo dateChooserComboIseBasladigiTarih;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxOgretmenmi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelBasliq;
    public javax.swing.JLabel jLabelPersonelNo;
    public javax.swing.JLabel jLabeldogum;
    public javax.swing.JLabel jLabeltarih;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBitirdigiOkul;
    private javax.swing.JTextField jTextFieldBrans;
    private javax.swing.JTextField jTextFieldMaas;
    private javax.swing.JTextField jTextFieldOgrenciAd;
    private javax.swing.JTextField jTextFieldOgrenciAdres;
    private javax.swing.JTextField jTextFieldOgrenciSoyad;
    private javax.swing.JTextField jTextFieldOgrenciTel1;
    private javax.swing.JTextField jTextFieldOgrenciTel2;
    private javax.swing.JTextField jTextFieldOgrenciTelNumarasi;
    // End of variables declaration//GEN-END:variables

    public void setPerNo()
    {
        this.jLabelPersonelNo.setText((new Functions()).getPerNumarasiString());
    }

    void setDuzenle(boolean b) {
        duzenle=b;
    }
}
